# Generated by Django 4.2 on 2025-07-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_loginlog_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ['-login_time'], 'verbose_name': 'Login Log', 'verbose_name_plural': 'Login Logs'},
        ),
        migrations.AddField(
            model_name='loginlog',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='was_successful',
            field=models.BooleanField(default=True),
        ),
    ]
