# Generated by Django 4.2 on 2025-08-12 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_loginlog_options_loginlog_failure_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='geofence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.geofence'),
        ),
    ]
