# Generated by Django 4.2 on 2025-08-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_geofence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
